In [ ]:
import numpy as np
u=np.array([2,3])
v=np.array([4,1])
print("u+v=",u+v)
print("3*u=",3*u)

u+v= [6 4]
3*u= [6 9]


In [ ]:
import numpy as np
student1 = np.array([85, 78, 90])
student2 = np.array([72, 88, 80])
student3 = np.array([95, 92, 87])
print(student1)
print(student2)
print(student3)

[85 78 90]
[72 88 80]
[95 92 87]


In [ ]:
import numpy as np
student1 = np.array([85, 78, 90])
student2 = np.array([72, 88, 80])
student3 = np.array([95, 92, 87])
print("L2 Norm of Student 1:", np.linalg.norm(student1))
print("L2 Norm of Student 2:", np.linalg.norm(student2))
print("L2 Norm of Student 3:", np.linalg.norm(student3))
print("Student 1 & Student 2:",
      np.dot(student1, student2) /
      (np.linalg.norm(student1) * np.linalg.norm(student2)))
print("Student 1 & Student 3:",
      np.dot(student1, student3) /
      (np.linalg.norm(student1) * np.linalg.norm(student3)))
print("Student 2 & Student 3:",
      np.dot(student2, student3) /
      (np.linalg.norm(student2) * np.linalg.norm(student3)))

# This cell (i0W2q0xBAz93) executed successfully without errors.
# A 'LinAlgError: Singular matrix' was observed in cell _oCM2DF6FHnw.

L2 Norm of Student 1: 146.31814651641812
L2 Norm of Student 2: 139.02517757586213
L2 Norm of Student 3: 158.29718885690926
Student 1 & Student 2: 0.9922373891772182
Student 1 & Student 3: 0.9965135938404224
Student 2 & Student 3: 0.9949428227480657


In [ ]:
import numpy as np

A = np.array([[1, 1, 1],
              [20, 50, 80],
              [1, 2, 3]])
B = np.array([100, 6000, 150])
X = np.linalg.solve(A, B)

print(X)

LinAlgError: Singular matrix